// Shared canonical dataset for TutorDexWebsite pages.
// Source of truth: TutorDexAggregator/extract_key_info.py (LEVELS / SPECIFIC_LEVELS / SUBJECTS).
// Exposed as globals for simple static hosting (no bundler needed).

window.tutorDexLevels = [
  "Pre-School",
  "Primary",
  "Secondary",
  "IGCSE",
  "IB",
  "Junior College",
  "Diploma",
  "Degree",
  "Olympiads",
  "Independent Learner - Languages",
  "Independent Learner - Computing",
  "Independent Learner - Music",
  "Independent Learner - Others",
];

window.tutorDexSpecificLevels = {
  "Pre-School": ["Nursery", "Kindergarten 1", "Kindergarten 2"],
  Primary: ["Primary 1", "Primary 2", "Primary 3", "Primary 4", "Primary 5", "Primary 6"],
  Secondary: ["Secondary 1", "Secondary 2", "Secondary 3", "Secondary 4", "Secondary 5"],
  IGCSE: ["Pre-IGCSE Grade 6", "Pre-IGCSE Grade 7", "Pre-IGCSE Grade 8", "IGCSE Grade 9", "IGCSE Grade 10"],
  IB: ["IB MYP Grade 6", "IB MYP Grade 7", "IB MYP Grade 8", "IB MYP Grade 9", "IB MYP Grade 10", "IB DP Year 1", "IB DP Year 2"],
  "Junior College": ["JC 1", "JC 2", "JC 3", "Private Candidate"],
  Diploma: ["Poly Year 1", "Poly Year 2", "Poly Year 3"],
  Olympiads: ["Primary School Olympiad", "Olympiads Secondary", "Olympiads JC"],
};

window.tutorDexSubjects = {
  "Pre-School": ["English", "Chinese", "Maths", "Phonics", "Creative Writing", "Malay", "Tamil"],
  Primary: [
    "English",
    "Maths",
    "Science",
    "Chinese",
    "Higher Chinese",
    "Malay",
    "Higher Malay",
    "Tamil",
    "Higher Tamil",
    "Hindi",
    "Creative Writing",
    "Phonics",
    "Maths Olympiad",
    "Science Olympiad",
  ],
  Secondary: [
    "English",
    "Chinese",
    "Higher Chinese",
    "Maths",
    "Science",
    "E Maths",
    "A Maths",
    "Physics",
    "Chemistry",
    "Biology",
    "Physics/Chem",
    "Bio/Physics",
    "Bio/Chem",
    "Geography",
    "History",
    "Literature",
    "Accounting (POA)",
    "Social Studies",
    "Geo/S.Studies",
    "Hist/S.Studies",
    "Malay",
    "Tamil",
    "Higher Malay",
    "Higher Tamil",
    "Hindi",
    "Music",
  ],
  "Junior College": [
    "General Paper",
    "Maths",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Accounting",
    "History",
    "Geography",
    "Literature",
    "Chinese",
    "Malay",
    "Tamil",
    "Chinese Studies",
    "Malay Studies",
    "Tamil Studies",
    "Knowledge & Inquiry",
    "Project Work",
    "Computing",
    "Art",
    "Theatre Studies & Drama",
    "Management of Business",
    "H3 Literature",
    "H3 Modern Physics",
    "H3 Chemistry",
    "H3 Proteomics",
    "H3 Maths",
    "H3 Geography",
    "H3 History",
    "H3 Economics",
    "Chinese Language and Literature",
    "Malay Language and Literature",
    "Tamil Language and Literature",
  ],
  "IB/IGCSE": [
    "English Language",
    "English Literature",
    "Chinese",
    "Mathematics",
    "Mathematical Studies",
    "Physics",
    "Chemistry",
    "Biology",
    "Business Management",
    "Economics",
    "Psychology",
    "Theory of Knowledge",
    "Extended Essay",
    "Theatre",
    "Environmental Systems",
    "Design Technology",
    "Geography",
    "History",
    "Malay",
    "Tamil",
    "Religious Knowledge",
    "Music",
    "Visual Arts",
    "Drama",
    "Art & Design",
    "IGTS",
  ],
  Diploma: [
    "Business & Finance",
    "Computing & Technology",
    "Engineering & Applied Sciences",
    "Health & Life Sciences",
    "Arts, Humanities & Social Sciences",
  ],
  Degree: [
    "Business & Finance",
    "Computing & Technology",
    "Engineering & Applied Sciences",
    "Health & Life Sciences",
    "Arts, Humanities & Social Sciences",
  ],
  Olympiads: [
    "Primary School Math Olympiads",
    "Primary School Science Olympiads",
    "SMO (Junior)",
    "SJPO",
    "SJCHO",
    "SJBO",
    "SMO (Senior)",
    "SMO (Open)",
    "SPHO",
    "SCHO",
    "SBO",
    "APHO",
    "IPHO",
    "IOI",
    "NRC",
  ],
  "Independent Learner - Languages": [
    "Japanese",
    "Korean",
    "French",
    "German",
    "Spanish",
    "Russian",
    "Italian",
    "English",
    "Chinese",
    "Portuguese",
    "Arabic",
    "Vietnamese",
    "Thai",
    "Indonesian",
    "Tagalog",
    "Hindi",
    "Bengali",
  ],
  "Independent Learner - Computing": [
    "Python",
    "C++",
    "C#",
    "Java",
    "JavaScipt",
    "ASP",
    "PHP",
    "VB",
    "MSSQL",
    "Oracle",
    "Photoshop",
    "Illustrator",
    "Autocad",
    "GIS",
    "3D Design",
    "Flash",
    "Web Design",
    "Linux",
    "Macintosh",
    "Solaris",
    "Windows",
    "MS Office",
    "MySQL",
  ],
  "Independent Learner - Music": [
    "Music Theory",
    "Piano",
    "Guitar",
    "Drum",
    "Violin",
    "Flute",
    "Clarinet",
    "Trumpet",
    "Saxophone",
    "Dance",
    "Gu Zheng",
  ],
  "Independent Learner - Others": ["Others"],
};

// Back-compat: earlier pages used `window.subjectsData`.
window.subjectsData = window.tutorDexSubjects;
