"""
Subject alias mapping (v1).

This replaces the legacy `validator.py` subject alias table and is used by:
- `TutorDexAggregator/extractors/subjects_matcher.py`

Keys are normalized to lowercase; values are canonical subject names as used by this repo.
"""

# Auto-generated from legacy validator.SUBJECT_ALIASES
SUBJECT_ALIASES = {
    'a math': 'A Maths',
    'a maths': 'A Maths',
    'a-math': 'A Maths',
    'a-maths': 'A Maths',
    'accounting': 'Accounting (POA)',
    'additional math': 'A Maths',
    'additional maths': 'A Maths',
    'amath': 'A Maths',
    'amaths': 'A Maths',
    'apho': 'APHO',
    'arabic': 'Arabic',
    'art': 'Art',
    'art and design': 'Art & Design',
    'bengali': 'Bengali',
    'bio': 'Biology',
    'bio/chem': 'Bio/Chem',
    'bio/phy': 'Bio/Physics',
    'biology': 'Biology',
    'biology & chemistry': 'Bio/Chem',
    'biology & physics': 'Bio/Physics',
    'biology and chemistry': 'Bio/Chem',
    'biology and physics': 'Bio/Physics',
    'business': 'Business Management',
    'business management': 'Business Management',
    'c#': 'C#',
    'c++': 'C++',
    'chem': 'Chemistry',
    'chem/bio': 'Bio/Chem',
    'chemistry': 'Chemistry',
    'chi': 'Chinese',
    'chinese': 'Chinese',
    'clarinet': 'Clarinet',
    'computer science': 'Computing',
    'computing': 'Computing',
    'creative writing': 'Creative Writing',
    'cs': 'Computing',
    'cw': 'Creative Writing',
    'drama': 'Drama',
    'drum': 'Drum',
    'drums': 'Drum',
    'e math': 'E Maths',
    'e maths': 'E Maths',
    'e-math': 'E Maths',
    'e-maths': 'E Maths',
    'economics': 'Economics',
    'econs': 'Economics',
    'ee': 'Extended Essay',
    'elementary math': 'E Maths',
    'elementary maths': 'E Maths',
    'emath': 'E Maths',
    'emaths': 'E Maths',
    'eng': 'English',
    'english': 'English',
    'english literature': 'Literature',
    'extended essay': 'Extended Essay',
    'flute': 'Flute',
    'french': 'French',
    'general paper': 'General Paper',
    'geo': 'Geography',
    'geog': 'Geography',
    'geography': 'Geography',
    'german': 'German',
    'gp': 'General Paper',
    'guitar': 'Guitar',
    'h3 biology': 'H3 Proteomics',
    'h3 chemistry': 'H3 Chemistry',
    'h3 economics': 'H3 Economics',
    'h3 geography': 'H3 Geography',
    'h3 history': 'H3 History',
    'h3 literature': 'H3 Literature',
    'h3 math': 'H3 Maths',
    'h3 maths': 'H3 Maths',
    'h3 physics': 'H3 Modern Physics',
    'hcl': 'Higher Chinese',
    'higher chinese': 'Higher Chinese',
    'higher malay': 'Higher Malay',
    'higher tamil': 'Higher Tamil',
    'hindi': 'Hindi',
    'hist': 'History',
    'history': 'History',
    'indonesian': 'Indonesian',
    'ioi': 'IOI',
    'ipho': 'IPHO',
    'it': 'Computing',
    'italian': 'Italian',
    'japanese': 'Japanese',
    'java': 'Java',
    'javascript': 'JavaScipt',
    'js': 'JavaScipt',
    'knowledge and inquiry': 'Knowledge & Inquiry',
    'korean': 'Korean',
    'linux': 'Linux',
    'lit': 'Literature',
    'literature': 'Literature',
    'mac': 'Macintosh',
    'macos': 'Macintosh',
    'malay': 'Malay',
    'management of business': 'Management of Business',
    'math': 'Maths',
    'math olympiad': 'Primary School Math Olympiads',
    'mathematics': 'Maths',
    'mathmatic': 'Maths',
    'mathmatics': 'Maths',
    'maths': 'Maths',
    'maths olympiad': 'Primary School Math Olympiads',
    'mssql': 'MSSQL',
    'music': 'Music',
    'music theory': 'Music Theory',
    'mysql': 'MySQL',
    'nrc': 'NRC',
    'oracle': 'Oracle',
    'phonics': 'Phonics',
    'php': 'PHP',
    'phy': 'Physics',
    'phy/chem': 'Physics/Chem',
    'phys': 'Physics',
    'phys/chem': 'Physics/Chem',
    'physics': 'Physics',
    'physics & chemistry': 'Physics/Chem',
    'physics and chemistry': 'Physics/Chem',
    'piano': 'Piano',
    'poa': 'Accounting (POA)',
    'portuguese': 'Portuguese',
    'principles of accounts': 'Accounting (POA)',
    'project work': 'Project Work',
    'pw': 'Project Work',
    'python': 'Python',
    'russian': 'Russian',
    'saxophone': 'Saxophone',
    'sbo': 'SBO',
    'scho': 'SCHO',
    'sci': 'Science',
    'sci.': 'Science',
    'science': 'Science',
    'science olympiad': 'Primary School Science Olympiads',
    'sjbo': 'SJBO',
    'sjcho': 'SJCHO',
    'sjpo': 'SJPO',
    'smo': 'SMO (Junior)',
    'smo jr': 'SMO (Junior)',
    'smo open': 'SMO (Open)',
    'smo senior': 'SMO (Senior)',
    'social studies': 'Social Studies',
    'spanish': 'Spanish',
    'spho': 'SPHO',
    'ss': 'Social Studies',
    'tagalog': 'Tagalog',
    'tamil': 'Tamil',
    'thai': 'Thai',
    'theatre': 'Theatre',
    'theatre studies': 'Theatre Studies & Drama',
    'theory of knowledge': 'Theory of Knowledge',
    'tok': 'Theory of Knowledge',
    'trumpet': 'Trumpet',
    'vietnamese': 'Vietnamese',
    'violin': 'Violin',
    'visual arts': 'Visual Arts',
    'windows': 'Windows',
}

# --------------------------------------------------------------------------------------
# Additional aliases (expanded; conservative mappings to current canonical subject names)
# --------------------------------------------------------------------------------------

SUBJECT_ALIASES.update(
    {
        # English
        "eng.": "English",
        "engl": "English",
        "english language": "English Language",
        "eng language": "English Language",
        "eng lang": "English Language",
        "el": "English Literature",
        "eng lit": "English Literature",
        "english lit": "English Literature",
        "lit.": "Literature",
        "lang & lit": "English Literature",
        "language & literature": "English Literature",
        "language and literature": "English Literature",

        # Maths / E Maths / A Maths
        "math.": "Maths",
        "maths.": "Maths",
        "mathematics.": "Maths",
        "e.math": "E Maths",
        "e.maths": "E Maths",
        "e-math.": "E Maths",
        "e-maths.": "E Maths",
        "elem math": "E Maths",
        "elem maths": "E Maths",
        "elementary mathematics": "E Maths",
        "elementary mathematics.": "E Maths",
        "a.math": "A Maths",
        "a.maths": "A Maths",
        "a-math.": "A Maths",
        "a-maths.": "A Maths",
        "add math": "A Maths",
        "add maths": "A Maths",
        "add. math": "A Maths",
        "add. maths": "A Maths",

        # Maths Olympiad / Science Olympiad
        "math olympiads": "Maths Olympiad",
        "maths olympiads": "Maths Olympiad",
        "math olympiad.": "Maths Olympiad",
        "maths olympiad.": "Maths Olympiad",
        "smo": "Maths Olympiad",
        "smo (junior)": "Maths Olympiad",
        "smo (senior)": "Maths Olympiad",
        "science olympiads": "Science Olympiad",
        "science olympiad.": "Science Olympiad",

        # Science / Combined sciences
        "sci": "Science",
        "sci .": "Science",
        "sci/phy": "Science",
        "sci/chem": "Science",
        "sci/bio": "Science",
        "combined science": "Science",
        "combined sciences": "Science",
        "chem.": "Chemistry",
        "phy.": "Physics",
        "phys.": "Physics",
        "bio.": "Biology",
        "physics chem": "Physics/Chem",
        "physics + chemistry": "Physics/Chem",
        "physics & chem": "Physics/Chem",
        "physics and chem": "Physics/Chem",
        "phys chem": "Physics/Chem",
        "phys/chem": "Physics/Chem",
        "bio chem": "Bio/Chem",
        "bio + chem": "Bio/Chem",
        "bio & chem": "Bio/Chem",
        "bio and chem": "Bio/Chem",
        "bio physics": "Bio/Physics",
        "bio + physics": "Bio/Physics",
        "bio & physics": "Bio/Physics",
        "bio and physics": "Bio/Physics",

        # Humanities
        "geo.": "Geography",
        "geog.": "Geography",
        "hist.": "History",
        "ss.": "Social Studies",
        "soc studies": "Social Studies",
        "social study": "Social Studies",
        "soc. studies": "Social Studies",
        "poa.": "Accounting (POA)",
        "accounts": "Accounting (POA)",
        "accounting poa": "Accounting (POA)",
        "principles of accounting": "Accounting (POA)",
        "principles of account": "Accounting (POA)",
        "acc": "Accounting (POA)",
        "econ": "Economics",
        "econs.": "Economics",
        "biz": "Business Management",
        "bm": "Business Management",

        # Mother tongue languages
        "cl": "Chinese",
        "chi.": "Chinese",
        "mt chinese": "Chinese",
        "mother tongue chinese": "Chinese",
        "hcl.": "Higher Chinese",
        "higher cl": "Higher Chinese",
        "ml": "Malay",
        "mt malay": "Malay",
        "bm (malay)": "Malay",
        "hml": "Higher Malay",
        "higher ml": "Higher Malay",
        "tl": "Tamil",
        "mt tamil": "Tamil",
        "htl": "Higher Tamil",
        "higher tl": "Higher Tamil",

        # Phonics / Creative Writing
        "phonic": "Phonics",
        "phonics.": "Phonics",
        "cw.": "Creative Writing",
        "creative writing.": "Creative Writing",
        "comp.": "Computing",
        "computer": "Computing",
        "computer studies": "Computing",

        # JC / IB terms (subjects)
        "gp.": "General Paper",
        "gen paper": "General Paper",
        "general paper.": "General Paper",
        "pw.": "Project Work",
        "project work.": "Project Work",
        "ki": "Knowledge & Inquiry",
        "knowledge & inquiry.": "Knowledge & Inquiry",
        "tok.": "Theory of Knowledge",
        "theory of knowledge.": "Theory of Knowledge",
        "ee.": "Extended Essay",
        "extended essay.": "Extended Essay",

        # Common misspellings / variants (keep small but useful)
        "econs": "Economics",
        "econ.": "Economics",
    }
)

