#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "GENERATED_INVENTORY.md"

SECTIONS = {
    "Components": ["TutorDexAggregator", "TutorDexBackend", "TutorDexWebsite", "shared", "observability", "scripts/ops"],
    "Ops Scripts": ["scripts/ops", "scripts"],
    "GitHub Workflows": [".github/workflows"],
    "Canonical Docs": ["AGENTS.md", "docs"],
}


def list_existing(paths: list[str]) -> list[str]:
    out: list[str] = []
    for rel in paths:
        path = ROOT / rel
        if path.is_file():
            out.append(rel)
        elif path.is_dir():
            for child in sorted(path.iterdir()):
                if child.is_file() and child.suffix in {".sh", ".py", ".yml", ".yaml", ".md"}:
                    out.append(str(child.relative_to(ROOT)))
    return out


def render() -> str:
    lines = [
        "# TutorDex Generated Inventory",
        "",
        "<!-- doc_lint:enforce -->",
        "Doc type: Generated reference",
        "",
        "**Docs metadata:**",
        "**Status:** active",
        "**Owner:** Mochi",
        "**Last reviewed:** 2026-06-17",
        "**Review trigger:** Regenerate with `python3 scripts/docs_inventory.py --write` when components, workflows, ops scripts, services, or canonical docs change.",
        "",
        "Generated by:",
        "",
        "```bash",
        "python3 scripts/docs_inventory.py --write",
        "```",
        "",
    ]
    for title, paths in SECTIONS.items():
        lines.append(f"## {title}")
        lines.append("")
        for rel in list_existing(paths):
            lines.append(f"- `{rel}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate compact TutorDex repo inventory.")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.write:
        OUT.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

